version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - /home/mireuser/Jellyfin/:/config
      - /home/mireuser/DockerData/JellyfinData/tvshows:/data/tvshows
      - /home/mireuser/DockerData/JellyfinData/movies:/data/movies
      - /home/mireuser/DockerData/JellyfinData/animes:/data/animes
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped